config/routes.rb
Rails.application.routes.draw do

	root 'sales#home'
   get '/sales/:site', to: 'sales#index', as: 'each_site_revenue'
	get '/sales/:site/:update_at', to: 'sales#show', as: 'detail_daily_revenue'
   get '/course/:site', to: 'courses#index', as: 'show_by_course'
	resources :courses, only: [:new, :create, :index, :show]
	resources :sales, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates_uniqueness_of :url
	has_many :sales, dependent: :destroy
end

app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   def index
      @each_course_accumulated_revenue = []
      @each_course_revenue = Sale.group(:course_id).sum(:daily_revenue).sort_by {|key, value| value}.reverse
      @each_course_revenue.each do |key, value|
         course = Course.find_by(id: key,
                                 site: params[:site])
         sale = Sale.find_by(course_id: key,
                             update_at: Time.now.strftime("%Y-%m-%d"))
         unless sale.nil? || course.nil?
            each_course = {id: key,
                           url: course.url,
                           title: course.title,
                           price: sale.price,
                           student_count: sale.student_count,
                           accumulated_revenue: value}
         end
         @each_course_accumulated_revenue << each_course
      end
   end

   def new
      create
   end

   def create
      InflearnCrawling.inflearn_crawling
      GoormCrawling.goorm_crawling
      redirect_to "/"
   end

   def show
      sql = "SELECT (A.student_count - B.student_count) AS student_change, A.student_count, A.update_at
		   	   FROM Sales A, Sales B
		   	   WHERE A.course_id = #{params[:id]} AND A.course_id = B.course_id AND A.update_at = B.update_at + interval '1 days' AND A.update_at > now() + interval '-7 days'
		   	   GROUP BY A.update_at, A.course_id, A.student_count, B.student_count
		   	   ORDER BY A.update_at"

      @course_student_change = Sale.find_by_sql(sql)
   end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
   def home
   end

   def index
      sql = "SELECT A.update_at, SUM((A.student_count - B.student_count) * A.price) AS revenue
               FROM Courses, Sales A, Sales B
               WHERE Courses.site = '#{params[:site]}' AND Courses.id = A.course_id AND A.course_id = B.course_id AND A.update_at = B.update_at + interval '1 days'
               GROUP BY A.update_at
               ORDER BY A.update_at DESC"

      @overview_daily_revenue = Sale.find_by_sql(sql)

      @monthly_revenue_predict = 0
      @overview_daily_revenue.each do |daily|
         @monthly_revenue_predict += daily.revenue * 0.3
      end
      @monthly_revenue_predict = ((@monthly_revenue_predict / @overview_daily_revenue.size * 9 * 365) / (10 * 12)).to_i
   end

   def show
      sql = "SELECT Courses.id, Courses.title, Courses.url, A.student_count, A.price, ((A.student_count - B.student_count) * A.price) AS revenue
               FROM Courses, Sales A, Sales B
               WHERE Courses.site = '#{params[:site]}' AND Courses.id = A.course_id AND A.course_id = B.course_id AND A.update_at = B.update_at + interval '1 days' AND A.update_at = '#{params[:update_at]}'
               ORDER BY revenue DESC"

      @detail_daily_revenue = Course.find_by_sql(sql)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/index.html.erb
<h4><%= params[:site]%></h4>

<ul>
  <table class="highlight">
    <thead>
    <tr>
      <th> Title</th>
      <th> 누적 파악 매출</th>
      <th> 누적 수강생</th>
      <th> 현재 가격</th>
    </tr>
    </thead>

    <% @each_course_accumulated_revenue.each do |course| %>
      <tbody>
      <tr>
        <% unless course.nil? %>
          <th><a href=<%= course[:url] %> target="_blank"> <%= course[:title] %> </a></th>
          <th> ₩ <%= number_with_delimiter(course[:accumulated_revenue], delimeter: ',') %> </th>
          <th> <%= number_with_delimiter(course[:student_count], delimeter: ',') %> 명</th>
          <th> ₩ <%= number_with_delimiter(course[:price], delimeter: ',') %> </th>
          <th> <%= link_to "상세보기", course_path(course[:id]) %> </th>
        <% end %>
      </tr>
      </tbody>
    <% end %>
  </table>
</ul>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<head>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1.1', {packages: ['corechart']});
    google.setOnLoadCallback(drawChart);

    function drawChart() {
      var data = new google.visualization.DataTable();

      data.addColumn('string', '날짜');
      data.addColumn('number', '수강생 변동');

      '<% @course_student_change.each do |daily| %>'
      var updateAt = '<%= daily.update_at %>';
      var studentCount = '<%= daily.student_change %>';
      data.addRows([[updateAt, parseInt(studentCount)]]);
      '<% end %>'

      var option = {
        vAxis: {
        	minValue: 0,
        	format: 'decimal', 
        	gridlines: { count: 2 }
        },
        width: 1000,
        height: 400,
        colors: ['black']
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart'));

      chart.draw(data, option);
    }

  </script>
</head>

<div id="chart" style="float:left"></div>
<div style="float:left">
	<ul>
		<table id="student_count_change_table" class="highlight">
			<thead>
				<tr>
					<th> 날짜 </th>
					<th> 누적 수강생 </th>
				</tr>
			</thead>

			<% @course_student_change.each do |daily| %>
			<tbody>
				<tr>
					<th>  <%= daily.update_at %> </th>
					<th>  <%= number_with_delimiter(daily.student_count, delimiter: ',') %> 명</th>
				</tr>
			</tbody>
			<% end %>
		</table>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grepp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper black">
        <%= link_to "Home",  root_path, style: "margin-left: 50px; font-size: 20px"%>
        <%= link_to "Inflearn",  each_site_revenue_path("inflearn"), style: "margin-left: 50px; font-size: 20px"%>
        <%= link_to "Goorm-edu",  each_site_revenue_path("goorm"), style: "margin-left: 50px; font-size: 20px"%>
        <ul class="right hide-on-med-and-down">
          <li><a href="/courses/new">Update</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/home.html.erb
<h1>home</h1>

app/views/sales/index.html.erb
<% if params[:site] == "inflearn" %>
  <h4>인프런 매출분석</h4>
<% else %>
  <h4>구름에듀 매출분석</h4>
<% end %>

<%= link_to "코스별", show_by_course_path(params[:site]), class: "btn" %>

<ul>
	<div id="overview_revenue" style="float:left">
		<table id="overview_revenue_table" class="highlight">
			<thead>
				<tr>
					<th> 날짜 </th>
					<th> 당일매출 </th>
					<th> 회사매출 </th>
				</tr>
			</thead>

			<% @overview_daily_revenue.each do |daily| %>
			<tbody>
				<tr>
					<th> <%= link_to daily.update_at, detail_daily_revenue_path(params[:site], daily.update_at) %> </th>
					<th> ₩ <%= number_with_delimiter(daily.revenue, delimiter: ',') %> </th>
					<th> ₩ <%= number_with_delimiter((daily.revenue * 0.3).to_i, delimiter: ',') %></th>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>

	<div style="float:left">
		<table id="monthly_revenue_predict_table" class="highlight">
			<thead>
				<tr>
					<th> 월간매출예상 </th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<th> ₩ <%= number_with_delimiter(@monthly_revenue_predict, delimiter: ',') %> </th>
				</tr>
			</tbody>
		</table>
	</div>
</ul>

app/views/sales/show.html.erb
<h4><%= params[:update_at] %></h4>

<input type="text" class="datepicker" value = <%= params[:update_at] %>>
<script>
  var site = '<%= params[:site] %>'
	$(function() {
		$( ".datepicker" ).datepicker({
			dateFormat: 'yyyy-mm-dd',
			onSelect: function(date) {
				var nextDate = date.getDate();
				var nextMonth = date.getMonth()+1;
				var nextYear = date.getFullYear();
				window.location.replace("/sales/" + site + "/" + nextYear + '-' + nextMonth + '-' + nextDate);
			}
		});
	})
</script>

<ul>
	<table class="highlight">
		<thead>
			<tr>
				<th> Title </th>
				<th> 수강생 </th>
				<th> 가격 </th>
				<th> 매출 </th>
			</tr>
		</thead>

		<% @detail_daily_revenue.each do |course| %>
		<tbody>
			<tr>
				<th> <a href=<%= course.url %> target="_blank"> <%= course.title %> </th>
					<th> <%= number_with_delimiter(course.student_count, delimeter: ',') %> 명 </th>
					<th> ₩ <%= number_with_delimiter(course.price, delimeter: ',') %> </th>
					<th> ₩ <%= number_with_delimiter(course.revenue, delimeter: ',') %> </th>
					<th> <%= link_to "상세보기", course_path(course.id) %> </th>
				</tr>
			</tbody>
			<% end %>
		</ul>